# Generated by Django 3.0.7 on 2020-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=300)),
                ('Date', models.DateField()),
                ('url', models.URLField(max_length=300)),
            ],
        ),
    ]
