# Generated by Django 3.0.7 on 2020-06-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='Description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
